#include <stdio.h>
/**
 * main - Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2
 * Fibonacci sequence values not exceed 4,000,000
 *
 * Return:0
 */
int main(void)
{
	long int a = 1, b = 2 sum = 0, res = 2;
	int val;

	while (sum <= 4000000)
	{
		sam = a + b;
		a = b;
		b = sum;
		if (sum % 2 == 0)
		{
			res += sum;
		}
	}
	printf("%li\n", res);
	return (0);
}
